apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonsets
  namespace: nginx
  annotations:
    owner: "avi"
    description: "demonset pods"
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-dae-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
