kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: practice
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: nginx-container-2
    image: nginx:latest
    ports:
    - containerPort: 81